import { Product } from './types';

export const PRODUCTS: Product[] = [
  // Combo Especial em Destaque
  {
    id: 'combo-1',
    name: 'Combo Completo: Burger + Batata Frita + Refri 2L',
    category: 'combos',
    price: 49.90,
    description: 'O combo campeão da casa! Acompanha 1 Suculento Hambúrguer Artesanal na brasa (blend Angus 180g com queijo cheddar inglês derretido) + 1 Porção generosa de Batatas Fritas rústicas crocantes e sequinhas + 1 Refrigerante de 2 Litros estupidamente gelado (Coca-Cola 2L ou Guaraná Antarctica 2L à sua escolha).',
    imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=1200&q=80',
    tag: 'Super Combo',
    prepTime: '20-25 min',
    weightOrVolume: 'Serve 1 a 2 pessoas',
    isPopular: true,
  },

  // 4 Hambúrgueres
  {
    id: 'burger-1',
    name: 'Smash Burger Clássico',
    category: 'burgers',
    price: 32.90,
    description: 'Pão brioche dourado na manteiga, 2 suculentos burgers smash de 90g (blend 100% Angus), queijo cheddar inglês derretido em camadas, picles crocantes artesanais e nossa maionese especial de alho assado.',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    tag: 'Mais Vendido',
    prepTime: '15-20 min',
    weightOrVolume: '180g carne',
    isPopular: true,
  },
  {
    id: 'burger-2',
    name: 'Bacon Cheddar Supremo',
    category: 'burgers',
    price: 39.90,
    description: 'Pão brioche selado, generoso burger artesanal de 180g grelhado no fogo, piscina de queijo cheddar cremoso, tiras crocantes de bacon defumado em lenha de macieira e cebola caramelizada artesanal.',
    imageUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=800&q=80',
    tag: 'Favorito do Chef',
    prepTime: '15-20 min',
    weightOrVolume: '180g carne',
    isPopular: true,
  },
  {
    id: 'burger-3',
    name: 'Monster BBQ Smoked',
    category: 'burgers',
    price: 44.90,
    description: 'Hambúrguer nobre de 200g na brasa, costela bovina desfiada marinada na cerveja preta com molho barbecue defumado da casa, anéis crocantes de cebola crispy, queijo prato derretido e rúcula fresca.',
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    tag: 'Defumado Especial',
    prepTime: '20-25 min',
    weightOrVolume: '200g carne',
    isPopular: false,
  },
  {
    id: 'burger-4',
    name: 'Trufado Gorgonzola & Cogumelos',
    category: 'burgers',
    price: 46.90,
    description: 'Pão australiano artesanal com toque de mel, burger de 180g de costela, creme aveludado de gorgonzola dolce, cogumelos Paris frescos salteados no azeite trufado e leve geleia de bacon levemente picante.',
    imageUrl: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=800&q=80',
    tag: 'Linha Gourmet',
    prepTime: '20-25 min',
    weightOrVolume: '180g carne',
    isPopular: false,
  },

  // 4 Refrigerantes
  {
    id: 'drink-1',
    name: 'Coca-Cola Original (Lata 350ml)',
    category: 'drinks',
    price: 7.50,
    description: 'O sabor clássico e refrescante que dispensa apresentações. Servida estupidamente gelada, acompanha copo térmico com pedras de gelo e rodela de limão taiti fresco.',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80',
    tag: 'Super Gelada',
    prepTime: 'Imediato',
    weightOrVolume: '350ml',
    isPopular: true,
  },
  {
    id: 'drink-2',
    name: 'Coca-Cola Zero Açúcar (Lata 350ml)',
    category: 'drinks',
    price: 7.50,
    description: 'O autêntico sabor marcante e refrescante de Coca-Cola sem nenhuma adição de açúcar e zero calorias. Servida em lata bem gelada com gelo e limão.',
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=800&q=80',
    tag: 'Zero Açúcar',
    prepTime: 'Imediato',
    weightOrVolume: '350ml',
    isPopular: false,
  },
  {
    id: 'drink-3',
    name: 'Guaraná Antarctica (Lata 350ml)',
    category: 'drinks',
    price: 6.90,
    description: 'O verdadeiro sabor do Brasil produzido com puro extrato do fruto do guaraná cultivado na Amazônia. Refrescância natural e energia equilibrada para o seu lanche.',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80',
    tag: 'Brasilidade',
    prepTime: 'Imediato',
    weightOrVolume: '350ml',
    isPopular: true,
  },
  {
    id: 'drink-4',
    name: 'Soda Limonada Antarctica (Lata 350ml)',
    category: 'drinks',
    price: 6.90,
    description: 'Refrigerante cítrico e efervescente com aroma suave e natural de limão. Perfeito para limpar o paladar e harmonizar com burgers artesanais queijos nobres.',
    imageUrl: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?auto=format&fit=crop&w=800&q=80',
    tag: 'Cítrico Leve',
    prepTime: 'Imediato',
    weightOrVolume: '350ml',
    isPopular: false,
  },
  {
    id: 'drink-5',
    name: 'Coca-Cola Original (Garrafa 2 Litros)',
    category: 'drinks',
    price: 15.90,
    description: 'Garrafa pet de 2 Litros tamanho família, estupidamente gelada com máximo gás e refrescância. Perfeita para acompanhar o seu combo.',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80',
    tag: 'Tamanho Família',
    prepTime: 'Imediato',
    weightOrVolume: '2 Litros',
    isPopular: true,
  },
  {
    id: 'drink-6',
    name: 'Guaraná Antarctica (Garrafa 2 Litros)',
    category: 'drinks',
    price: 13.90,
    description: 'Garrafa pet de 2 Litros bem gelada do clássico guaraná da Amazônia. Sabor e efervescência para dividir com quem você gosta.',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80',
    tag: 'Tamanho Família',
    prepTime: 'Imediato',
    weightOrVolume: '2 Litros',
    isPopular: false,
  },

  // 4 Sobremesas
  {
    id: 'dessert-1',
    name: 'Brownie Fudge com Sorvete',
    category: 'desserts',
    price: 22.90,
    description: 'Brownie artesanal denso feito com puro chocolate belga 70% e nozes crocantes, servido quentinho acompanhado de uma bola de sorvete artesanal de creme e calda quente de chocolate.',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    tag: 'Queridinho da Casa',
    prepTime: '5-10 min',
    weightOrVolume: '220g',
    isPopular: true,
  },
  {
    id: 'dessert-2',
    name: 'Milkshake de Nutella & Ninho',
    category: 'desserts',
    price: 24.90,
    description: 'Batido na hora com sorvete premium de baunilha de Madagascar, dose generosa de Nutella pura, leite em pó Ninho legítimo e finalizado com montanha de chantilly fresco e raspas de avelã.',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80',
    tag: 'Cremoso Especial',
    prepTime: '5-8 min',
    weightOrVolume: '400ml',
    isPopular: true,
  },
  {
    id: 'dessert-3',
    name: 'Pudim Tradicional de Leite Condensado',
    category: 'desserts',
    price: 14.90,
    description: 'Fatia individual generosa do clássico pudim caseiro: textura ultra aveludada, sem furinhos, banhado em uma farta calda de caramelo dourado com toque de baunilha.',
    imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80',
    tag: 'Receita da Vovó',
    prepTime: 'Imediato',
    weightOrVolume: '160g',
    isPopular: false,
  },
  {
    id: 'dessert-4',
    name: 'Petit Gâteau com Calda de Frutas Vermelhas',
    category: 'desserts',
    price: 26.90,
    description: 'Bolo fofo individual de chocolate nobre com recheio cremoso que escorre ao cortar, servido com bola de sorvete de baunilha e coulis artesanal de morangos, amoras e mirtilos.',
    imageUrl: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=800&q=80',
    tag: 'Sobremesa Chef',
    prepTime: '10-12 min',
    weightOrVolume: '200g',
    isPopular: false,
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'Todos os Itens', icon: 'UtensilsCrossed' },
  { id: 'combos', label: 'Combos', icon: 'Sparkles' },
  { id: 'burgers', label: 'Hambúrgueres', icon: 'Flame' },
  { id: 'drinks', label: 'Refrigerantes', icon: 'GlassWater' },
  { id: 'desserts', label: 'Sobremesas', icon: 'IceCream' },
] as const;

export const FEATURED_COMBO = {
  id: 'combo-1',
  name: 'Combo Completo: Burger + Batata Frita + Refri 2L',
  price: 49.90,
  originalPrice: 65.90,
  discountAmount: 16.00,
  description: '1 Hambúrguer Artesanal na brasa + 1 Porção de Batatas Fritas crocantes + 1 Refrigerante de 2 Litros geladíssimo.',
  imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=1200&q=80',
  items: [
    {
      title: 'Hambúrguer Artesanal',
      detail: 'Blend Angus 180g na brasa com cheddar derretido',
      emoji: '🍔',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    },
    {
      title: 'Batatas Fritas Crocantes',
      detail: 'Douradas, sequinhas e crocantes com sal e ervas finas',
      emoji: '🍟',
      imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    },
    {
      title: 'Refrigerante 2 Litros',
      detail: 'Garrafa pet 2L estupidamente gelada à sua escolha',
      emoji: '🥤',
      imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
    },
  ],
};

export const RESTAURANT_INFO = {
  name: 'Burger & Co. Artesanal',
  tagline: 'Hambúrgueres na brasa, bebidas geladas & sobremesas irresistíveis',
  address: 'Rua dos Sabores, 120 - Centro',
  hours: 'Terça a Domingo das 18h às 23h30',
  phone: '(35) 98895-7259',
  whatsappNumber: '5535988957259',
  whatsappDisplay: '(35) 98895-7259',
  deliveryFee: 6.90,
  minOrder: 20.00,
  estimatedDelivery: '35 - 50 min',
  estimatedPickup: '15 - 25 min',
};
